#!/usr/bin/env python3
"""llms-txt-generator.py — generate an llms.txt route map for a repo.

Companion to *Software Engineering with AI*, Ch 6 §6.5.3 (llms.txt as a repo route map
that points an agent at the files that matter). Walks the repo top levels and emits an
llms.txt skeleton listing key entry points and per-area README links.

Usage:
  python3 scripts/llms-txt-generator.py path/to/repo > llms.txt
  python3 scripts/llms-txt-generator.py .            # current repo to stdout
"""
import sys, pathlib

KEY_FILES = ["README.md","CLAUDE.md","AGENTS.md","CONTRIBUTING.md","package.json",
             "pyproject.toml","go.mod","Cargo.toml"]
SKIP = {".git","node_modules","dist","build",".venv","__pycache__",".next"}

def main():
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    name = root.name
    out = [f"# {name}", "", "> Route map for AI agents (Ch 6 §6.5.3). Generated by "
           "scripts/llms-txt-generator.py — edit by hand to add intent and pointers.", ""]
    out.append("## Key files")
    for kf in KEY_FILES:
        if (root/kf).exists(): out.append(f"- [{kf}]({kf})")
    out.append("")
    out.append("## Areas")
    for d in sorted(p for p in root.iterdir() if p.is_dir() and p.name not in SKIP
                    and not p.name.startswith(".")):
        readme = "README.md" if (d/"README.md").exists() else None
        link = f"{d.name}/{readme}" if readme else f"{d.name}/"
        out.append(f"- [{d.name}/]({link}) — TODO: one line on what lives here")
    out.append("")
    out.append("## Conventions")
    out.append("- TODO: verify command, test layout, naming, anything an agent must know.")
    print("\n".join(out))

if __name__ == "__main__":
    main()
